djangoapp/blog/urls.py
from django.urls import path
from blog.views import PageDetailView, PostDetailView, SearchListView, PostListView, CreatedByListView, CategoryListView, TagListView

app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name='index' ),
    path('post/<slug:slug>/', PostDetailView.as_view(), name='post' ),
    path('page/<slug:slug>/', PageDetailView.as_view(), name='page' ),
    path('created_by/<int:author_pk>/', CreatedByListView.as_view(), name='created_by' ),
    path('category/<slug:slug>/', CategoryListView.as_view(), name='category' ),
    path('tag/<slug:slug>/', TagListView.as_view(), name='tag' ),
    path('search/', SearchListView.as_view(), name='search' ),
]

djangoapp/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('blog.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

djangoapp/blog/models.py
from audioop import reverse
from django.db import models
from utils.rands import slugify_new
from django.contrib.auth.models import User
from utils.images import resize_image
from django_summernote.models import AbstractAttachment
from django.urls import reverse

class PostAttachment(AbstractAttachment):
    def save(self, *args, **kwargs):
        if not self.name:
            self.name = self.file.name

        current_favicon_name = str(self.file.name)
        super_save = super().save(*args, **kwargs)
        favicon_changed = False

        if self.file:
            favicon_changed = current_favicon_name != self.file.name
        
        if favicon_changed:
            resize_image(self.file, 900, True, 70)

        return super_save
        

class Tag(models.Model):
    class Meta:
        verbose_name = 'Tag'
        verbose_name_plural = 'Tags'


    name = models.CharField(max_length=255)
    slug = models.SlugField(
        unique=True, default=None,
        null=True, blank=True, max_length=255,
    )

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify_new(self.name, 4)
        return super().save(*args, **kwargs)

    def __str__(self) -> str:
        return self.name
    
class Category(models.Model):
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


    name = models.CharField(max_length=255)
    slug = models.SlugField(
        unique=True, default=None,
        null=True, blank=True, max_length=255,
    )

    def __str__(self) -> str:
        return self.name
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify_new(self.name, 4)
        return super().save(*args, **kwargs)

class Page(models.Model):
    class Meta:
        verbose_name = 'Page'
        verbose_name_plural = 'Pages'

    title = models.CharField(max_length=65,)
    slug = models.SlugField(
        unique=True, default="",
        null=False, blank=True, max_length=255
    )
    is_published = models.BooleanField(
        default=False,
        help_text=(
            'Este campo precisará estar marcado '
            'para a página ser exibida publicamente.'
        ),
    )
    content = models.TextField()

    def __str__(self) -> str:
        return self.title
    
    def get_absolute_url(self):
        if not self.is_published:
            return reverse('blog:index')
        return reverse('blog:page', args=(self.slug,))
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify_new(self.title, 4)
        return super().save(*args, **kwargs)

class PostManager(models.Manager):
    def get_published(self):
        return self\
            .filter(is_published=True)\
            .order_by('-pk')

class Post(models.Model):
    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'

    objects = PostManager()

    title = models.CharField(max_length=65,)
    slug = models.SlugField(
        unique=True, default="",
        null=False, blank=True, max_length=255
    )
    excerpt = models.CharField(max_length=150)
    is_published = models.BooleanField(
        default=False,
        help_text=(
            'Este campo precisará estar marcado '
            'para a página ser exibida publicamente.'
        ),
    )
    content = models.TextField()
    cover = models.ImageField(upload_to='posts/%Y/%m', blank=True, default='')
    cover_in_post_content = models.BooleanField(
        default=True,
        help_text='Se marcado, exibirá a capa dentro o post.',
    )
    created_at = models.DateTimeField(auto_now_add=True)
    # user.post_by.all
    created_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        blank=True, null=True,
        related_name='page_created_by'
    )
    updated_at = models.DateTimeField(auto_now=True)
    # user.post_updated_by.all
    updated_by = models.ForeignKey(
        User, on_delete=models.SET_NULL,
        null=True, blank=True,
        related_name='page_updated_by',
    )

    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, blank=True,
        default=None,
    )
    tags = models.ManyToManyField(Tag, blank=True, default='')

    def __str__(self) -> str:
        return self.title
    
    def get_absolute_url(self):
        if not self.is_published:
            return reverse('blog:index')
        return reverse('blog:post', args=(self.slug,))

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify_new(self.title, 4)

        current_favicon_name = str(self.cover.name)
        super_save = super().save(*args, **kwargs)
        favicon_changed = False
        if self.cover:
            favicon_changed = current_favicon_name != self.cover.name
        
        if favicon_changed:
            resize_image(self.cover, 900, True, 70)

        return super_save
    

djangoapp/blog/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import redirect, render
from django.core.paginator import Paginator
from blog.models import Post, Page
from django.db.models import Q
from django.contrib.auth.models import User
from django.http import Http404
from django.views.generic import ListView, DetailView

posts = list(range(1000))
PER_PAGE = 9

class PostListView(ListView):
    model = Post
    template_name = 'blog/pages/index.html'
    context_object_name = 'posts'
    ordering = '-pk',
    paginate_by = PER_PAGE
    queryset = Post.objects.get_queryset()
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context.update({
            'page_title': 'Home - ',
        })

        return context

# def index(request):
#     posts = Post.objects.get_published() # type:ignore

#     paginator = Paginator(posts, PER_PAGE)
#     page_number = request.GET.get("page")
#     page_obj = paginator.get_page(page_number)

#     return render(
#         request,
#         'blog/pages/index.html',
#         {
#             'page_obj': page_obj,
#             'page_title': 'Home - ',
#         }

#     )

class CreatedByListView(PostListView):
    def __init__(self, **kwargs: Any) -> None:
        super().__init__(**kwargs)
        self._temp_context: dict[str, Any] = {}

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        user = self._temp_context['user']
        user_full_name = user.username

        if user.first_name:
            user_full_name = f'{user.first_name} {user.last_name}'
        page_title = 'Posts de ' + user_full_name + ' - '

        ctx.update({
            'page_title': page_title,
        })

        return ctx

    def get_queryset(self) -> QuerySet[Any]:
        qs = super().get_queryset()
        qs = qs.filter(created_by__pk=self._temp_context['user'].pk)
        return qs

    def get(self, request, *args, **kwargs):
        author_pk = self.kwargs.get('author_pk')
        user = User.objects.filter(pk=author_pk).first()

        if user is None:
            raise Http404()

        self._temp_context.update({
            'author_pk': author_pk,
            'user': user,
        })

        return super().get(request, *args, **kwargs)

# def created_by(request, author_pk):
#     user = User.objects.filter(pk=author_pk).first()

#     if user is None:
#         raise Http404

#     posts = (Post.objects.get_published() # type:ignore
#             .filter(created_by__pk=author_pk)
         
#         )
#     user_full_name = user.username

#     if user.first_name:
#         user_full_name = f'{user.first_name} {user.last_name}'

#     page_title = 'Posts de ' + user_full_name + ' - '

#     paginator = Paginator(posts, PER_PAGE)
#     page_number = request.GET.get("page")
#     page_obj = paginator.get_page(page_number)

#     return render(
#         request,
#         'blog/pages/index.html',
#         {
#             'page_obj': page_obj,
#             'page_title': page_title,
#         }

#     )

class CategoryListView(PostListView):
    allow_empty = False
    def get_queryset(self) -> QuerySet[Any]:
        return super().get_queryset().filter(
            category__slug=self.kwargs.get('slug')
        )
    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        page_title = (f'{self.object_list[0].category.name} - Categoria - ') # type: ignore
        ctx.update({
            'page_title': page_title,
        })
        return ctx

# def category(request, slug):
#     posts = (Post.objects.get_published() # type:ignore
#             .filter(category__slug=slug) 
#         ) 

#     paginator = Paginator(posts, PER_PAGE)
#     page_number = request.GET.get("page")
#     page_obj = paginator.get_page(page_number)

#     if len(page_obj) == 0:
#         raise Http404

#     page_title = f'{page_obj[0].category.name} - Categoria - '

#     return render(
#         request,
#         'blog/pages/index.html',
#         {
#             'page_obj': page_obj,
#             'page_title': page_title,
#         }

#     )

class SearchListView(PostListView):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._search_value = ''

    def setup(self, request, *args, **kwargs):
        self._search_value = request.GET.get('search', '').strip()
        return super().setup(request, *args, **kwargs)
    
    def get_queryset(self) -> QuerySet[Any]:
        search_value = self._search_value
        return super().get_queryset().filter(
            Q(title__icontains=search_value) |
            Q(excerpt__icontains=search_value) |
            Q(content__icontains=search_value)
            )[:PER_PAGE]

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        search_value = self._search_value       
        ctx.update({
            'page_title': f'{search_value[:30]} - Search - ',
            'search_value': search_value,
        })
        return ctx
    
    def get(self, request, *args, **kwargs):
        if self._search_value == '':
            return redirect('blog:index')
        return super().get(request, *args, **kwargs)

# def search(request):
#     search_value = request.GET.get('search', '').strip()

#     posts = (Post.objects.get_published() # type:ignore
#             .filter(
#                 Q(title__icontains=search_value) |
#                 Q(excerpt__icontains=search_value) |
#                 Q(content__icontains=search_value)
#             ) [0:PER_PAGE]
#         ) 

#     page_title = f'{search_value[:30]} - Search - '


#     return render(
#         request,
#         'blog/pages/index.html',
#         {
#             'page_obj': posts,
#             'search_value': search_value,
#             'page_title': page_title,
#         }

#     )

class TagListView(PostListView):
    allow_empty = False

    def get_queryset(self) -> QuerySet[Any]:
        return super().get_queryset().filter(
            tags__slug=self.kwargs.get('slug')
        )
    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        page_title = (f'{self.object_list[0].tags.first().name} - Tag - ') # type: ignore
        ctx.update({
            'page_title': page_title,
        })
        return ctx    

# def tag(request, slug):
#     posts = (Post.objects.get_published() # type:ignore
#             .filter(tags__slug=slug) 
#         ) 

#     paginator = Paginator(posts, PER_PAGE)
#     page_number = request.GET.get("page")
#     page_obj = paginator.get_page(page_number)

#     if len(page_obj) == 0:
#         raise Http404

#     page_title = f'{page_obj[0].tags.first().name} - Tag - '

#     return render(
#         request,
#         'blog/pages/index.html',
#         {
#             'page_obj': page_obj,
#             'page_title': page_title,
#         }

#     )

class PageDetailView(DetailView):
    model = Page
    template_name = 'blog/pages/page.html'
    slug_field = 'slug'
    context_object_name = 'page'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        ctx = super().get_context_data(**kwargs)
        page = self.get_object()
        page_title = f'{page.title} - Página - ' # type:ignore
        ctx.update({
            'page_title': page_title,
        })
        return ctx
    
    def get_queryset(self) -> QuerySet[Any]:
        return super().get_queryset().filter(is_published=True)

# def page(request, slug):
#     page_obj = (
#         Page.objects
#         .filter(is_published=True)
#         .filter(slug=slug)
#         .first()
#     )

#     if page_obj is None:
#         raise Http404

#     page_title = f'{page_obj.title} - Página - '

#     return render(
#         request,
#         'blog/pages/page.html',
#         {
#             'page': page_obj,
#             'page_title': page_title,
#         }

#     )

class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/pages/post.html'
    slug_field = 'slug'
    context_object_name = 'post'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        ctx = super().get_context_data(**kwargs)
        post = self.get_object()
        page_title = f'{post.title} - Post - ' # type:ignore
        ctx.update({
            'page_title': page_title,
        })
        return ctx
    
    def get_queryset(self) -> QuerySet[Any]:
        return super().get_queryset().filter(is_published=True)


# def post(request, slug):
#     post_obj = (
#         Post.objects.get_published() # type:ignore
#         .filter(slug=slug)
#         .first()
#     )

#     if post_obj is None:
#         raise Http404

#     page_title = f'{post_obj.title} - Post - ' 
    
#     return render(
#         request,
#         'blog/pages/post.html',
#         {
#             'post': post_obj,
#             'page_title': page_title,
#         }

#     )

djangoapp/blog/templates/blog/partials/_footer.html
<footer class="footer section-wrapper mt-base">
    <div class="section-content-wide">
      <div class="section-gap">
        <div class="center">
          <a href="#"> © {% now "Y" %} {{ site_setup.title}} - Todos os direitos reservados. </a>
        </div>
      </div>
    </div>
</footer>

<script>
  (function () {
    if (typeof CodeMirror == 'undefined') return;

    const codes = document.querySelectorAll('pre');

    for (const code of codes) {
      const language = code.dataset.language || null;
      const text = code.textContent || code.innerText;

      const config = {
        value: text,
        tabSize: 2,
        mode: language,
        theme: 'dracula',
        lineNumbers: true,
        styleActiveLine: true,
        styleActiveSelected: true,
        lineWrapping: false,
        line: true,
        readOnly: true,
        viewportMargin: 50,
        matchBrackets: true,
      };

      const editor = CodeMirror(function (node) {
        code.parentNode.replaceChild(node, code);
      }, config);
    }
  })();
</script>

djangoapp/blog/templates/blog/partials/_head.html
{% load static %}
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" href="{% static 'blog/css/remedy.css' %}">
<link rel="stylesheet" href="{% static 'blog/css/style.css' %}">

{% if site_setup.favicon %}
  <link rel="shortcut icon" href="{{ site_setup.favicon.url }}" type="image/png">
{% endif %}

<title>{{ page_title }}{{ site_setup.title }}</title>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

djangoapp/blog/templates/blog/partials/_header.html
<header class="header section-wrapper">
  <div class="section-content-wide">
    <div class="section-gap">

      <h1 class="blog-title center pb-base">
        <a class="blog-link" href="/"> {{ site_setup.title }} </a>
      </h1>
      
      {% if site_setup.show_description %}
        <p class="blog-description pb-base center">{{ site_setup.description }}</p>
      {% endif %}

      {% if site_setup.show_search %}
        <div class="search pb-base center">
          <form class="search-form" action="{% url "blog:search" %}" method="get">
            <div class="search-content">
              <label class="sr-only" id="search-label" for="search-input">Search</label>
              <input
                class="search-input"
                type="search"
                name="search"
                id="search-input"
                placeholder="Search"
                value="{{ search_value }}"
                required
              >
              <button class="search-btn" type="submit" aria-labelledby="search-label">
                <i class="fa fa-search"></i>
              </button>
            </div>
          </form>
        </div>
      {% endif %}

      {% if site_setup.show_menu %}
          <nav class="menu">
            <ul class="menu-items">
              {% for link in site_setup.menu.all %}
                <li class="menu-item">
                  {% if link.new_tab %}
                    <a target="_blank" class="menu-link" href="{{ link.url_or_path }}">
                      {{ link.text }}
                    </a>
                {% else %}
                    <a class="menu-link" href="{{ link.url_or_path }}">
                      {{ link.text }}
                    </a>
                  {% endif %}
                </li>
              {% endfor %}
            </ul>
          </nav>
        {% endif %}    
      
    </div>
  </div>
</header>

djangoapp/blog/templates/blog/partials/_pagination.html
{% if page_obj and page_obj.has_other_pages %}

<div class="separator"></div>

<div class="pagination-wrapper section-wrapper">
  <div class="pagination-content section-content-wide">
    <div class="pagination-gap section-gap">

      <nav class="pagination-links" aria-label="Pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
              <a title="Page 1" aria-label="Page 1" href="?page=1{{ search_url }}">
                  <i class="fa-solid fa-backward-fast"></i>
              </a>
              <a title="Page {{ page_obj.previous_page_number }}" aria-label="Page {{ page_obj.previous_page_number }}" href="?page={{ page_obj.previous_page_number }}{{ search_url }}">
                <i class="fa-solid fa-circle-chevron-left"></i>
              </a>
            {% else %}
              <span title="Current page" aria-current="page">
                <i class="fa-solid fa-circle-chevron-up"></i>
              </span>          
            {% endif %}

            <span class="current" title="Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}" aria-current="page">
              {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}
            </span>

            {% if page_obj.has_next %}
              <a title="Page {{ page_obj.next_page_number }}" aria-label="Page {{ page_obj.next_page_number }}" href="?page={{ page_obj.next_page_number }}{{ search_url }}">
                <i class="fa-solid fa-circle-chevron-right"></i>
              </a>
              <a title="Page {{ page_obj.paginator.num_pages }}" aria-label="Page {{ page_obj.paginator.num_pages }}" href="?page={{ page_obj.paginator.num_pages }}{{ search_url }}">
                <i class="fa-solid fa-forward-fast"></i>
              </a>
            {% else %}
              <span title="Current page" aria-current="page">
                <i class="fa-solid fa-circle-chevron-up"></i>
              </span>          
            {% endif %}
        </span>
      </nav>
      
    </div>
  </div>
</div>

{% endif %}

djangoapp/blog/templates/blog/partials/_post-card.html
<article class="card">
  
  {% if post.cover %}
    <div class="card-cover-wrapper">
      <a href="{{ post.get_absolute_url }}" class="card-cover-link">
        <img 
          class="card-cover"
          loading="lazy"
          src="{{ post.cover.url }}" 
          alt="Cover do post {{ post.title }}"
        >
      </a>
    </div>
  {% endif %}

  <div class="card-text-wrapper">
    <div class="card-title-wrapper">
      <h2 class="card-title">
        <a href="{{ post.get_absolute_url }}" class="card-title-link">
          {{ post.title }}
        </a>
      </h2>
    </div>

    <div class="card-content-wrapper">
      <p class="card-content">
        {{ post.excerpt }}
      </p>

      <div class="card-actions">
        <a class="card-action-link" href="{{ post.get_absolute_url }}">
          <span>Read</span>
          <i class="fa-solid fa-circle-arrow-right"></i>
        </a>
      </div>
    </div>
  </div>

</article>